# Generated by Django 5.0.7 on 2025-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigachat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light_theme', 'light theme'), ('dark_theme', 'dark theme')], max_length=255, verbose_name='theme')),
            ],
        ),
    ]
