# Generated by Django 5.0.7 on 2025-05-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gigachat', '0002_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
