# Generated by Django 5.0.7 on 2025-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gigachat', '0004_setting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_who',
            field=models.TextField(verbose_name='from_who'),
        ),
    ]
